{{- if $.Values.mariadb.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-creds
  labels:
    {{- include "app.labels" . | nindent 8 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  mariadb-password: {{ randAlphaNum 32 | b64enc | quote }}
  mariadb-root-password: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}