{{- if $.Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  resources:
    requests:
      storage: {{ $.Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
{{- end }}