
{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ include "hub.name" . }}
  labels:
  {{- include "hub.labels" . | nindent 4 }}
data:
    {{- with .Values.config }}
    {{- toYaml . | nindent 2 }}
    {{- end }}
{{- end }}