
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hub.name" . }}
  labels:
    {{- include "hub.labels" . | nindent 4 }}
spec:
  replicas: {{ $.Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "hub.name" . }}
  template:
    metadata:
      labels:
          app: {{ include "hub.name" . }}
    spec:
      {{- if .Values.initContainer }}
      initContainers:
        - name: run-installer
          image: {{ include "hub.image" . }}
          command: {{ .Values.initContainer.command }}
      {{- end }}
      containers:
      - name: main
        image: {{ include "hub.image" . }}        
        env: 
        - name: WORDPRESS_DB_HOST
          value: {{ template "app.db.name" . }}
        - name: WORDPRESS_DB_USER
          value: {{ template "app.db.user" . }}
        - name: WORDPRESS_DB_NAME
          value: {{ template "app.db.database" . }}
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "app.db.usersecret" . }}
              key: {{ include "app.db.passkey" . }}
        {{ include "app.env" . | nindent 8 }}
        ports:
          - name: http
            containerPort: {{ $.Values.service.port }}
            protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop: ['ALL']
          seccompProfile:
            type: RuntimeDefault
        livenessProbe:
          {{- toYaml $.Values.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml $.Values.readinessProbe | nindent 12 }}
        startupProbe:
          {{- toYaml $.Values.startupProbe | nindent 12 }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.volume.enabled }}
        volumeMounts:
          - name: data
            mountPath: {{ $.Values.volume.path }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "hub.name" . }}
      {{ end }}


        
