{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hub.name" . }}
  labels:
    {{- include "hub.labels" . | nindent 4}}
spec:
  ingressClassName: apps
  rules:
  - host: {{ include "hub.domain" . }}
    http:
      paths:
      - path: {{ $.Values.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "hub.name" . }}
            port: 
              number: {{ $.Values.service.port }}
  tls:
  - hosts:
      - {{ include "hub.domain" . }}
{{ end }}