apiVersion: v2
name: wordpress
description: Wordpress for Sprint
type: application

dependencies:
  - name: mariadb
    version: "~20.0.0"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mariadb.enabled