replicaCount: 1

image:
  name: wordpress

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: false
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

podEnv:
  - name: WORDPRESS_DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mariadb
        key: mariadb-password
  - name: WORDPRESS_DB_HOST
    value: mariadb
  - name: WORDPRESS_DB_NAME
    value: wordpress
  - name: WORDPRESS_DB_USER
    value: wordpress
  - name: WORDPRESS_DEBUG
    value: 'true'
securityContext: 
   capabilities:
     drop:
     - ALL
   readOnlyRootFilesystem: false
   runAsNonRoot: true

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  requests:
      cpu: 250m
      memory: 256Mi
  limits:
      cpu: 500m
      memory: 512Mi

# Temp probes
livenessProbe:
  httpGet:
    path: /license.txt
    port: http
readinessProbe:
  httpGet:
    path: /license.txt
    port: http

persistence:
  enabled: true
  size: 5Gi
  mountPath: /var/www/html/wp_content

# Additional volumes on the output Deployment definition.
volumes: []

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

mariadb:
  enabled: true
  fullnameOverride: mariadb
  architecture: standalone
  auth:
    rootPassword: ""
    database: wordpress
    username: wordpress
    password: ""
  primary:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 2Gi
    resources:
       requests:
         cpu: 250m
         memory: 256Mi
       limits:
         cpu: 500m
         memory: 512Mi